#!/bin/bash

CMD="docker run -t -i -h my-mailer \
	-p 25:25 -p 143:143 -p 587:587 -p 4190:4190 -p 993:993 -p 465:465 \
	-v /home/mail-data:/data \
	-v /home/postfix-spool:/var/spool/postfix/ \
	dropz-one/my-mailer"

echo $CMD "$@"
exec $CMD "$@"
