#!/bin/bash

case $1 in
        --test)
                TEST=1
        ;;
esac

NOW=$(date +'%s')

TWO_MONTH_AGO=$(date '+%Y' -d @$(( $NOW - 3600*24*31   )) )
ONE_MONTH_AGO=$(date '+%Y' -d @$(( $NOW - 3600*24*31*2 )) )

#TODO: for USER in $(/usr/local/bin/manage user-list)
for USER in edouard@vanbelle.fr
do
        # XXX: savedbefore OR before ?

        # archive
        QUERY="mailbox INBOX SEEN UNFLAGGED before 62days"

        echo "$USER: archive old mails to Archive/$TWO_MONTH_AGO"
        if [ -z $TEST ]
        then
                # create folder + subscribe
                doveadm mailbox create -u edouard@vanbelle.fr Archive/$TWO_MONTH_AGO 2>/dev/null
                # move
                doveadm -v move -u $USER Archive/$TWO_MONTH_AGO $QUERY
        else
                doveadm search -u $USER $QUERY
        fi


        # expunge 1 month old Junk 
	# Important: prefer 'savedbefore' rather 'before'
	for BOX in Junk Trash
	do
		QUERY="mailbox $BOX savedbefore 31days"
		echo "$USER: expunging old $BOX mails"
		if [ -z $TEST ]
		then
			doveadm -v expunge -u $USER $QUERY
		else
			doveadm search -u $USER $QUERY
		fi
	done

        ## expunge 2 month old Unsure
	echo "$USER: expunging old Unsure mails"
	QUERY="mailbox Unsure savedbefore 62days"
	if [ -z $TEST ]
	then
        	doveadm expunge -u $USER $QUERY
	else
		doveadm search -u $USER $QUERY
	fi

        echo
done
